### ISSUE TITLE
Can you open all your source code for iOS?

### ISSUE THREAD

**Issue by munrocket** [cybertim/blockwallet#22]
Hello devs, we really need trusted app on iOS that support ERC20 token.
As i understand your app is pretty cool, but not fully open source.
We already have trusted mobile app for bitcoin, but not for Ethereum!

**Comment by cybertim** [comment]
The main reason only the library is opensourced is because I used parts of the UI from my commercial project. Everything is in the Repo, all code 'touching', generation, signing the key and communicating with the rpc is available. Only the UI part is not open. Also, there have already been requests for audits but till now nobody is interested, because it is of course possible to give a serious auditing person private access to the complete Repo.

**Comment by munrocket** [comment]
We need independent audit and interest will appear. I don't think that UI it is the most intristing part, so... you can think again about opensource contribution to the crypto community.

If so I will buy your application in iOS. Now we do not have good wallets that supporting all erc20 token.
