### ISSUE TITLE
QR code changes when sharing

### ISSUE THREAD

**Issue by rytido** [cybertim/blockwallet#26]
The QR code appears to change when sharing the receiving address via message, mail, etc.

**Comment by cybertim** [comment]
Could you elaborate on 'code changed' ? For instance, do you mean the 'drawing' itself or the actual contents of the QRcode?

**Comment by rytido** [comment]
The drawing itself changes. Text stays the same.

**Comment by cybertim** [comment]
Ok, checked it myself, the text is different.

If you use the share button no checksum is added to the Ethereum address.
The qrcode on the receive screen does have the checksum added, hence the difference in the qrcode layout.

This will be fixed in the next update; sharing will also get the checksum and thus making the qrcodes the same.

**Comment by cybertim** [comment]
This has been fixed in version 2.0 (now available in the play/app store).
