### ISSUE TITLE
Ethereum balance incorrect, showing 0 ETH?

### ISSUE THREAD

**Issue by ghost** [cybertim/blockwallet#28]
Checked in my wallet this morning shows a 0 balance WTF. So checked and there is no record of transactions out of the wallet. 

It was a small amount of ethereum but am now questioning safety of the wallet.. is this a common issue my ether are completely gone and there is no transaction showing. I haven't sent any and it is not possible for someone to have used my phone and pin. Umber as it has been on my person at all times ... help?

**Comment by cybertim** [comment]
No worries, the blockwallet server is currently re-syncing, should be done within a few hours, if you refresh then all should be OK.
If the yellow banner on top of https://www.blockwallet.eu is gone, the server should be in sync.

Also, no ether is 'gone', it is only the balance calculation which is now incorrect because the server blockwallet uses by default is not yet fully synced. If you use another RPC server or simply check your balance on MyEtherWallet, you will see everything is there.

**Comment by ghost** [comment]
Ah just saw the syncing issue... thanks for help

**Comment by cybertim** [comment]
I re-opened it so other people can see this while the server is till syncing. Will close it when the syncing is done :-)
