### ISSUE TITLE
Blockwallet 

### ISSUE THREAD

**Issue by hooka123** [cybertim/blockwallet#30]
Coins transferred to Blockwallet address ,coins not showing in wallet

**Comment by cybertim** [comment]
you really need to supply more information, like at least a transaction hash? without such information the problem cloud literally be anything... unrelated to blockwallet that is.

**Comment by hooka123** [comment]
Sorry new to this does this help TxHash:0x13f9c2b3cc73704c1bd96957d937780d922b12dd33b5d1ad3e7224c28a48b6ec

**Comment by cybertim** [comment]
https://etherscan.io/tx/0x13f9c2b3cc73704c1bd96957d937780d922b12dd33b5d1ad3e7224c28a48b6ec

You probably bought some 'NAGA Coin'- tokens, you need to use the token tracker in the blockwallet app to see the value.

I added the NAGA Coin to the popular token list since it has an opensource contract. So you can now select it from the list and add it to the tracker - then it will show.

**Comment by hooka123** [comment]
Thank you very much coins are now showing
