### ISSUE TITLE
Request A Token For The Popular List Here!

### ISSUE THREAD

**Issue by cybertim** [cybertim/blockwallet#38]
Is a Token missing from the Popular List?

Reply in this thread with the following and I will add it:
- Token Name and
- Token Contract Address
or a link to the Contract on Etherscan.io

_Note:_ When a token has been added to the list it is instant available in the App.
But the list is cached, so if it doesn't show up in your App you can try closing (killing) the App and restart or clear the cache (Android) or as a last resort Restart the device (iOS) or just wait for a while :-)

**Comment by hooka123** [comment]
Hi could you please add  travelflex  TRF.  To the popular list 
 
Thanks

**Comment by cybertim** [comment]
Please supply the Token Contract Address for TRF or a link to the Contract on Etherscan.io.

**Comment by deerdear** [comment]
Hi! Could you add:

* CrowdstartCoin (Ticker: XSC)
* https://etherscan.io/token/0x0f513ffb4926ff82d7f60a05069047aca295c413

Thanks!

**Comment by cybertim** [comment]
XSC has been added.

**Comment by deerdear** [comment]
Cool! Thanks! Will it pop up in the next release or just automatically?

**Comment by cyber-jo** [comment]
please add Crypterium (CRPT)
https://crypterium.io/
thanks

**Comment by cybertim** [comment]
CRPT has been added:
https://etherscan.io/address/0x80a7e048f37a50500351c204cb407766fa3bae7f#readContract

**Comment by cyber-jo** [comment]
Hello, please, help me!
From crypterium.io i’ve received 294.84433 crypterium token. For this transaction I’ve provided my block-wallet address.
But i can’t see my balance on the ios-app.. and can’t deposit or withdrawn crpt-token.
Please take a look on etherscan:
https://etherscan.io/address/0xC7DeE2eD60dF05958E99cE1DF2D23ab1877F8f24#tokentxns
Please give me instructions to lose the problem.
Thanks!

**Comment by cybertim** [comment]
Did you add the token to the Overview with the aid of the Token Management (from the menu ☰) ?
If so, does the Value list as 0? And if you click 'Receive' and visit Etherscan.io from that screen in App, does it go to the same address as the link provided (and thus show the CRPT value)?

**Comment by cyber-jo** [comment]
Hello,
Thank you for your help
No, I gave to crypterium.io simply the ETH Address of the Block Wallet IOS App.. 0xC7DeE2eD60dF05958E99cE1DF2D23ab1877F8f24
If I go through menu -> manage token ->  +.. and I search for CRPT Tokens… I find nothings

**Comment by cybertim** [comment]
Ah, ok, you need to add CRPT first before you will see the value, and also get the options to transfer.
But when a token is added to the Popular list it can take a while (App cache) before it shows up.
You could [force close the App](https://support.apple.com/en-us/HT201330) to speed up the process.
It's also possible to add the Token manually, you can scan the CRPT contract addresses QR-code:
![unknown](https://user-images.githubusercontent.com/5379564/35591442-3f194d10-060a-11e8-88a8-c5de5d041b69.png)

**Comment by cyber-jo** [comment]
Perfekt! Thanks!!
It’s working!!

**Comment by cyber-jo** [comment]
Please add ELIX
elixirtoken.io
Thanks

**Comment by cybertim** [comment]
ElixerToken has been added:
https://etherscan.io/address/0xc8C6A31A4A806d3710A7B38b7B296D2fABCCDBA8#readContract

**Comment by cyber-jo** [comment]
please add HAT
https://www.hawala.today/
thanks

**Comment by quake3a** [comment]
@cybertim 
Hi! 
Please add Dmarket Token:
Token Symbol - DMT
Token Contract Address - 0x2ccbFF3A042c68716Ed2a2Cb0c544A9f1d1935E1  
Decimals - 8 
Thanks

**Comment by cybertim** [comment]
@quake3a DMT has been added.

**Comment by benzino225** [comment]
Hello
can you please add this to the token list

Name:Bitfincoin
ERC20 Contract Address: 0x50C68620a583bc2760F22711E28824eE4eE059D2
Token Decimals: 18
Symbol: BIC

**Comment by benzino225** [comment]
@cybertim 
Hello
can you please add this to the token list
Name:Bitfincoin
ERC20 Contract Address: 0x50C68620a583bc2760F22711E28824eE4eE059D2
Token Decimals: 18
Symbol: BIC

**Comment by benzino225** [comment]
Please I transferred my Bitfincoin in this ethereum wallet and till now I can't retrieve it....kindly help me
0x95d9a18845a82E0aa796496a0C3Bb1dB8dBAde3f

**Comment by ciphs** [comment]
Hi, as requested.

Name: Ciphs
Symbol: CIPHS
Address: https://etherscan.io/token/0xa4ff5ce0556f9ff0797ae525ec5ba9b723878a3e

Thanks in forward.

**Comment by hooka123** [comment]
Could you add to list:
Lucyd - 0x9a4059c1cf329a017e0ee1337c503137Fd9463b2
Faceter-0x1ccaa0f2a7210d76e1fdec740d5f323e2e1b1672
Thank you

**Comment by cybertim** [comment]
@ciphs @hooka123 
Ciphs, Lucyd and Faceter have been added.

**Comment by someone2026** [comment]
Could you add:

SocialX - SOCX - 0x587c549c4113127340ac0f5e996cab7a4f35bb49
Thanks

**Comment by cybertim** [comment]
@1000goalgaming has been added.

**Comment by cryptune** [comment]
Hi! Could you add:

Cryptune (Ticker: CPT)

https://etherscan.io/token/0x5797a6291c3f22f785bc6b793d023ef034a17719


Thanks!

**Comment by cybertim** [comment]
@cryptune CPT has been added to the list.

**Comment by cyber-jo** [comment]
Hello,
The e-mail You sent is blocked because it’s recognized as spam. To reach the recipient, please pay 5 USD via Paypal following this link.
Your payment will automatically unlock the email that will be delivered properly.
If Your message is considered as no spam by the recipient, the sum You paid will be refunded. Otherwise, Your email address will be registered on our servers and permanently blocked for all our customers. Thanks.
Note: sending less or more than 5 USD will result in the loss of your money and the email will remain blocked.
 
SPAMPOLICE ®

**Comment by cyber-jo** [comment]
Hello,
The e-mail You sent is blocked because it’s recognized as spam. To reach the recipient, please pay 5 USD via Paypal following this link.
Your payment will automatically unlock the email that will be delivered properly.
If Your message is considered as no spam by the recipient, the sum You paid will be refunded. Otherwise, Your email address will be registered on our servers and permanently blocked for all our customers. Thanks.
Note: sending less or more than 5 USD will result in the loss of your money and the email will remain blocked.
 
SPAMPOLICE ®

**Comment by cyber-jo** [comment]
Hello,
The e-mail You sent is blocked because it’s recognized as spam. To reach the recipient, please pay 5 USD via Paypal following this link.
Your payment will automatically unlock the email that will be delivered properly.
If Your message is considered as no spam by the recipient, the sum You paid will be refunded. Otherwise, Your email address will be registered on our servers and permanently blocked for all our customers. Thanks.
Note: sending less or more than 5 USD will result in the loss of your money and the email will remain blocked.
 
SPAMPOLICE ®

**Comment by johnsmith187** [comment]
requesting to add Regium to the wallet.
https://etherscan.io/token/0x9996a0b4d0d7ed1b7e41ad08bdc4acb198e232a9
Logo: https://regium.xyz/gallery_gen/5f9033a7fd14e2d82346bc2d7eab1bd4.png
